---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  become: true

  tasks:
    - name: Shutdown the instance
      virt:
        name: "{{ item.name }}"
        command: shutdown
        state: shutdown
      loop: "{{ molecule_yml.platforms }}"
      ignore_errors: true

    - name: Destroy the instance
      virt:
        name: "{{ item.name }}"
        command: destroy
        state: destroyed
      loop: "{{ molecule_yml.platforms }}"
      ignore_errors: true

    - name: 'Delete NVRAM of Instance'
      include_tasks:
        file: destroy_nvram.yml
      loop: "{{ molecule_yml.platforms }}"

    - name: Undefine the instance
      virt:
        name: "{{ item.name }}"
        command: undefine
      loop: "{{ molecule_yml.platforms }}"
      ignore_errors: true

    - name: Delete image file of the instance
      file:
        path: "{{ item.image_file_path }}"
        state: absent
      loop: "{{ molecule_yml.platforms }}"
