FROM {{ item.image }}

ENV DEBIAN_FRONTEND=noninteractive

# Install Python3
RUN apt update && apt -y install python3 python3-pip

# Install Init and SystemD
RUN apt -y install init systemd socket && \
    apt -y autoremove && apt clean

# Install OpenSSH-Server
RUN apt -y -u install openssh-server
