FROM {{ item.image }}

{% for var, value in (item.env | default({})).items() %}
ENV {{ var }} {{ value }}
{% endfor %}
ENV DEBIAN_FRONTEND=noninteractive

# Install Python3 & OpenSSH-Server
RUN apt-get update && apt-get -y install python3 python3-pip openssh-server
